config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  root 'static_pages#home'
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post 'login',     to: 'sessions#create'
  delete 'logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :bookmarklists , :savedposts
    end
  end

  resources :users do 
    resources :bookmarklists do 
      get :savedposts
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :bookmarklists, only: [:create , :destroy]
  resources :savedposts, only: [:create , :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Demo App by Yash
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class = "container">
        <%= link_to image_tag("home_background.png" , class:"logo") + "WeShare", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to 'Bookmarks' , bookmarklists_user_path(current_user) %></li>
              <li class = "dropdown">
                <a href = "#", class = "dropdown-toggle" data-toggle = "dropdown">
                  Account<b class = "caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Profile', user_path(current_user) %></li>
                  <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                  <li class = 'divider'></li>
                  <li><%= link_to 'Log out', logout_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <% end %>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <!-- does it enable us for flash popups? -->
        <% flash.each do |message_type, message| %>
          <%= content_tag :div, class: "alert alert-#{message_type}" do %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= message %>
          <% end %>
        <% end %>
      <%= yield %>
    </div>
  </body>

</html>